module.exports = {
    MESSAGE: 'MESSAGE',
    AGENTASSIGNED: 'AGENTASSIGNED',
    TOKEN: 'TOKEN',
    OFFLINE: 'OFFLINE',
    STARTCONVERSATION: 'STARTCONVERSATION',
    AGENTLEFT: 'AGENTLEFT',
    LEAVECHAT: 'LEAVECHAT',
    CONNECT: 'connect',
    ERROR: 'error'
};