const E = {
    MESSAGE: 'MESSAGE',
    MESSAGESEEN: 'MESSAGESEEN',
    AGENTASSIGNED: 'AGENTASSIGNED',
    ROOMASSIGNED: 'ROOMASSIGNED',
    NEWCHATASSIGNED: 'NEWCHATASSIGNED',

    TOKEN: 'TOKEN',
    ONLINE: 'ONLINE',
    OFFLINE: 'OFFLINE',
    STARTCONVERSATION: 'STARTCONVERSATION',
    VISITORCONNECTED: 'VISITORCONNECTED',
    VISITORDISCONNECTED: 'VISITORDISCONNECTED',
    VISITORLEFTCHAT: 'VISITORLEFTCHAT',
    LEAVECHAT: 'LEAVECHAT',
    AGENTLEFT: 'AGENTLEFT',
    JOINCHAT: 'JOINCHAT',
    VISITORTYPING: 'VISITORTYPING',
    SNEAKPREVIEW: 'SNEAKPREVIEW',
    RATECHAT: 'RATECHAT',
    ACTIVECHATCLOSED: 'ACTIVECHATCLOSED',
    STARTEDCONVERSATION: 'STARTEDCONVERSATION',
    MESSAGESDELETED: 'MESSAGESDELETED',
};

export default E;